// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for banners documents */
interface BannersDocumentData {
    /**
     * Imagem para pc field in *banners*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banners.background_image_pc
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image_pc: prismicT.ImageField<never>;
}
/**
 * banners document from Prismic
 *
 * - **API ID**: `banners`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BannersDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BannersDocumentData>, "banners", Lang>;
export type AllDocumentTypes = BannersDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BannersDocumentData, BannersDocument, AllDocumentTypes };
    }
}
